### ISSUE TITLE
Limiting the value decimals / precision?

### ISSUE THREAD

**Issue by hiatsu0** [Sese-Schneider/ha-energy-overview-card#24] opened 2023-03-06 16:42 UTC
Is there a way to control the decimals shown in the card? The precision provided by Shelly EM3 for instance seems a little excessive..and cannot be modified in the device afaik. Would not want to create template sensors for this.

Or alternatively, could the card follow the new `Display precision` setting in UI (new feature in 2023.3 I think). It already seems to be obeying the `Unit of measurement` set in the UI (f.ex. the `kW` figures were originally presented as `W` and I changed them in the UI dialog).

![image](https://user-images.githubusercontent.com/66969014/223172737-d9f2d2bc-de89-441f-a0f9-91eb2c97049a.png)

(and yes, my current clamps are still installed the wrong way around:)

**Comment by Sese-Schneider** [comment] 2023-03-06 17:06
Hi @hiatsu0,
thank you for your issue. I will have a look at why the display precision is not obeyed.

**Comment by jacobstim** [comment] 2023-03-06 20:05
Thanks for having a look at it @Sese-Schneider! As a followup to bug #9 I also discovered that even when using the proposed decimal value settings in HA, the energy overview card unfortunately keeps showing too many digits :).

**Comment by Sese-Schneider** [comment] 2023-03-07 11:46
@hiatsu0 @jacobstim the issue is finally fixed in `v2.4.1`.
Indeed, I did not support the display precision, as implementation was not trivial after the HA core update.
I now added support for sensor display precision and local number formats.

**Comment by hiatsu0** [comment] 2023-03-07 20:33
@Sese-Schneider Thank you, that was fast! Looks way better now without excessive decimals.

However, a small regression I noticed after updating: The power factors do not show percentages anymore, but constant zero instead. (Could maybe be just related to the fact that my factors are negative values, as I still have not had time to turn my current clamps right way around)

![image](https://user-images.githubusercontent.com/66969014/223545567-ce5f1ce9-cc81-4342-b841-8504142bee5e.png)

**Comment by Sese-Schneider** [comment] 2023-03-07 20:42
@hiatsu0 can you give me a screenshot of the power factors entity UI?
I want to know the `unit_of_measurement`, `precision` and `value`. 
I will investigate.

**Comment by Sese-Schneider** [comment] 2023-03-07 20:47
It does look ok on my test card:

|Card|Entity|Settings|
|-|-|-|
|![image](https://user-images.githubusercontent.com/14337484/223548329-fd72439a-6db4-49fa-8c13-caeed5b09e92.png)|![image](https://user-images.githubusercontent.com/14337484/223548497-1819d6df-ddb2-4195-915f-168af1c28274.png)|![image](https://user-images.githubusercontent.com/14337484/223548451-bcbb3d85-c42c-447d-acb7-90b0d3d3de9f.png)|

Please make sure the `unit_of_measurement` is either not set for values between -1 and 1, or set to `%` for values between -100 and 100

**Comment by hiatsu0** [comment] 2023-03-08 07:23
![F971D980-8861-4CA6-A861-4BAA80589130](https://user-images.githubusercontent.com/66969014/223647458-37e0bdeb-d62a-4958-8d3a-d1e25f1e4c98.jpeg)

![332CECF4-A084-44B1-84F8-76310642F668](https://user-images.githubusercontent.com/66969014/223647728-30270f60-d244-464c-90cb-df921bf214b8.jpeg)

The entity is generated by Shelly integration.

**Comment by hiatsu0** [comment] 2023-03-08 12:21
Could it be just the local decimal symbol: The state has ”0.X” but in lovelace it is displayed ”0,X”

**Comment by jacobstim** [comment] 2023-03-08 14:55
I can confirm that on my installation, the values are displayed correctly as well:

![image](https://user-images.githubusercontent.com/15199644/223745917-eef098e5-306e-4a0b-8319-0f4b82f1bf4a.png)

![image](https://user-images.githubusercontent.com/15199644/223746207-e43682eb-3085-4d12-a432-a3bc54a7f588.png)

@hiatsu0, do you do still some conversion in a template sensor to get the power factor percentages?

**Comment by Sese-Schneider** [comment] 2023-03-09 12:04
@hiatsu0 I found your issue, and indeed @jacobstim was right. I had to do with your number format having a `,` instead of a `.`, and a bad implementation on my side.
The primary issue for me here was, that I need to support numbers between -100 and 100, and between -1 and 1. This causes some complication in the implementation.

Nevertheless, I have fixed the issue as well, you can keep your number format at `,`, and it should work just fine, even with display precision support!
The release is out, thanks for reporting the bug.

**Closed by Sese-Schneider** 2023-03-09 12:04 UTC
Labels: bug, help wanted, released

**Comment by Sese-Schneider** [comment] 2023-03-09 12:08
Screenshot for reference:
![image](https://user-images.githubusercontent.com/14337484/224018836-b28e63e3-6541-458f-b3bc-de139e989473.png)

**Comment by hiatsu0** [comment] 2023-03-09 14:41
Confirmed fixed, thank you!
